apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - online-boutique.yaml

images:
  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/frontend
    newName: ghcr.io/hamza5839/online-boutique-cicd
    newTag: 6bde4bdf3fc4c24d69baf8e53148fec24fe0d660
