apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique-dev

resources:
  - ../../base
  - namespace.yaml

replicas:
  - name: frontend
    count: 2
  - name: loadgenerator
    count: 0
patches:
  - path: frontend-service-patch.yaml
