name: CI learnings
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  APP_NAME: frontend
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check required frontend files
        working-directory: app/frontend
        run: |
          test -f Dockerfile
          test -f go.mod
          test -f go.sum
          echo "All required files exist"

  build:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Read workflow variable again
        run: echo "Building $APP_NAME"
